[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
directories = "5.0.1"
owo-colors = "4.1.0"
serde = {version = "1.0.216", features = ["derive"]}
tabled = "0.17.0"

